import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/layout/Navbar";
import { CurrencyProvider } from "@/context/CurrencyContext";
import { CartProvider } from "@/context/CartContext";
import { AuthProvider } from "@/context/AuthContext";
import { OrdersProvider } from "@/context/OrdersContext";
import { Toaster } from "@/components/ui/sonner";
import Footer from "@/components/layout/Footer";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Acme Store",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body
        className={`${montserrat.variable} font-montserrat antialiased scroll-smooth`}
      >
        <NextIntlClientProvider>
          <AuthProvider>
            <OrdersProvider>
              <CartProvider>
                <CurrencyProvider>
                  <Navbar />
                  <main>{children}</main>
                  <Toaster />
                  <Footer />
                </CurrencyProvider>
              </CartProvider>
            </OrdersProvider>
          </AuthProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
